export const Users = [
  {
    id:1,
    profilePicture: "person/profile_1.jpg",
    fullName: "Safak Kocaoglu",
    userName: "safak76",
    friends: 5,
  },
  {
    id:2,
    profilePicture: "person/profile_2.jpg",
    fullName: "Janell Shrum",
    userName: "janell456",
    friends: 8,
  },
  {
    id:3,
    profilePicture: "person/profile_3.jpg",
    fullName: "Alex Durden",
    userName: "alex_durden22",
    friends: 11,
  },
  {
    id:4,
    profilePicture: "person/profile_4.jpg",
    fullName: "Dora Hawks",
    userName: "dorahawks87",
    friends: 1,
  },
  {
    id:5,
    profilePicture: "person/profile_5.jpg",
    fullName: "Thomas Holden",
    userName: "thomas66",
    friends: 35,
  },
  {
    id:6,
    profilePicture: "person/profile_6.jpg",
    fullName: "Shirley Beauchamp",
    userName: "beauchamp90",
    friends: 75,
  },
  {
    id:7,
    profilePicture: "person/profile_7.jpg",
    fullName: "Travis Bennett",
    userName: "tennett009",
    friends: 45,
  },
  {
    id:8,
    profilePicture: "person/profile_8.jpg",
    fullName: "Kristen Thomas",
    userName: "kristen88",
    friends: 52,
  },
  {
    id:9,
    profilePicture: "person/profile_9.jpg",
    fullName: "Gary Duty",
    userName: "dutycalls247",
    friends: 1,
  },
  {
    id:10,
    profilePicture: "person/profile_10.jpg",
    fullName: "Sean Kraig",
    userName: "kraig76",
    friends: 25,
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "post/post_image_1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "post/post_image_2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "post/post_image_3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "post/post_image_4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "post/post_image_5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "post/post_image_6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "post/post_image_7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "post/post_image_8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "post/post_image_9.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "post/post_image_10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
